force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <description>Este objeto almacena todas las películas disponibles en nuestra org</description>
    <label>Movie</label>
    <nameField>
        <label>Movie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/Director__c.field-meta.xml
<CustomField>
    <fullName>Director__c</fullName>
    <label>Director</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Image_Preview__c.field-meta.xml
<CustomField>
    <fullName>Image_Preview__c</fullName>
    <label>Image Preview</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Muy Buena</fullName>
            </value>
            <value>
                <fullName>Buena</fullName>
            </value>
            <value>
                <fullName>Regular</fullName>
            </value>
            <value>
                <fullName>Mala</fullName>
            </value>
            <value>
                <fullName>Muy Mala</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MovieListService.cls
public with sharing class MovieListService {
    @AuraEnabled(cacheable=true)

    public static List<Movie__c> getFilterMovies(String searchText) {
        String likeValue = '%' + searchText + '%';

        return [
            SELECT Id, Name, Rating__c, Director__c, Release_Date__c, Description__c, Image_Preview__c 
            FROM Movie__c
            WHERE Name LIKE : likeValue
        ];
    }
}